// Generated by CoffeeScript 1.4.0
(function() {
  var app, http;

  http = require('http');

  app = require('./app');

  http.createServer(app).listen(app.get('port'), function() {
    return console.log("Express server listening on port " + app.get('port'));
  });

}).call(this);
